### ISSUE TITLE
Issues with airplanemovie in examples 1, and 2

### ISSUE THREAD

**Issue by bmxmonkey33** [flavioluiz/AeroFlex#12]
First of all I want to say, this is some fantastic work.

I'm having some issues generating the simulations for examples 1 and 2,

I get the same error for both:

Index exceeds matrix dimensions.

Error in Airplane/airplanemovie (line 190)
                    translate = [0,0,kinetic_RB(i,4)-kinetic_RB(1,4)];

Error in example1 (line 121)
    airplanemovie(ap, ts, Xs,[],dt,'test','gif'); colormap winter;

I've done my best to figure out what is happening, and I've come to the conclusion that the empty matrix term is not being handled properly when handed over to the Airplane file here (Starting at line 194):

` if ~isempty(kinetic_RB)
                    for i_member = 1:ap.NUMmembers;
                            rotate(plotid(i_member),directionx,kinetic_RB(i,1)*180/pi);
                            rotate(plotid(i_member),directiony,kinetic_RB(i,2)*180/pi);
                        end
                    end`
Somewhere in this section. I am probably missing something, but I am not sure. I'm able to get the simulation to work by replacing the term in the translate function with another zero, but i know this is probably not the proper way to solve the problem. 

If you have any idea about what I should do, I would appreciate a response.

My matlab version is R2016b if that helps

Thank you!

**Comment by Jmmondragon** [comment]
I am having the same issue. Where exactly did you place the zero?

**Comment by flavioluiz** [comment]
Hi! 
Thank you very much for your interest. Sorry for the long delay, I was travelling and without Matlab in my personal computer. 

I've just implemented the correction. You are right, there was a problem when kinetic_RB was empty (which is the case in the first examples, since there are no rigid body DOFs!).

It is weird that it used to work in previous versions of Matlab, it seems that they changed how to deal with empty matrices (and it actually makes more sense now, I was accessing an empty matrix using kinetic_RB(i,4) in line 190).

Please tell me if you have any other problems.
Best regards,
Flavio
